steps:
  - name: "sonarsource/sonarcloud-scan:latest"
    id: "Sonar analysis"
    secretEnv:
      - "SONAR_TOKEN"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        sonar-scanner \
          -Dsonar.organization=mttcabral \
          -Dsonar.projectKey=mttcabral_technical-interview-ivory \
          -Dsonar.sources=. \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$$SONAR_TOKEN \
          -Dsonar.qualitygate.wait=true \
          -Dsonar.qualitygate.timeout=300

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    waitFor: ["Sonar analysis"]
    id: "Deploy GCS"
    entrypoint: "gcloud"
    args:
      - "storage"
      - "rsync"
      - "-r"
      - "--delete-unmatched-destination-objects"
      - "."
      - "gs://mttcabral-site"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/sonar-token/versions/latest
      env: "SONAR_TOKEN"

options:
  logging: CLOUD_LOGGING_ONLY
