steps:
  # ----------------------------
  # CI pipeline definition
  # ----------------------------

  - name: "gcr.io/cloud-builders/npm"
    id: "Install dependencies"
    args: ["install"]

  - name: "gcr.io/cloud-builders/npm"
    id: "Run tests"
    args: ["test"]

  - name: "gcr.io/cloud-builders/wget"
    id: "Download Sonar Scanner"
    args:
      - "https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip"
      - "-O"
      - "sonar-scanner.zip"

  - name: "alpine"
    id: "Unzip Sonar Scanner"
    args: ["unzip", "sonar-scanner.zip"]
    waitFor: ["Download Sonar Scanner"]

  - name: "./sonar-scanner-4.7.0.2747-linux/bin/sonar-scanner"
    id: "SonarCloud Scan"
    # Espera pelos testes e pela descompactação
    waitFor: ["Run tests", "Unzip Sonar Scanner"]
    args:
      - "-Dsonar.login=$(SONAR_TOKEN)"
      - "-Dsonar.qualitygate.wait=true"
      - "-Dsonar.qualitygate.timeout=300"
    secretEnv: ["SONAR_TOKEN"]

  # ----------------------------
  # CD pipeline definition
  # ----------------------------

  - name: "gcr.io/cloud-builders/docker"
    id: "Build image"
    waitFor: ["SonarCloud Scan"]
    args:
      - "build"
      - "-t"
      - "southamerica-east1	-docker.pkg.dev/$PROJECT_ID/my-docker-repo/hello-world:$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: "Send image"
    waitFor: ["Build image"]
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/hello-world:$COMMIT_SHA",
      ]

  - name: "gcr.io/google-cloud-sdk/gcloud"
    id: "Deploy in Cloud Run"
    waitFor: ["Send image"]
    args:
      - "run"
      - "deploy"
      - "technical-interview-ivory-service"
      - "--image=southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/hello-world:$COMMIT_SHA"
      - "--region=southamerica-east1"
      - "--platform=managed"
      - "--allow-unauthenticated"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/sonar-token/versions/latest
      env: "SONAR_TOKEN"

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - "southamerica-east1-docker.pkg.dev/$PROJECT_ID/my-docker-repo/hello-world:$COMMIT_SHA"
